#include "../include/rtl_generator.h"

void generate_verilog_module(ModuleConfig *config, FILE *output_file) {
    int i;
    
    fprintf(output_file, "// Auto-generated Verilog module\n");
    fprintf(output_file, "// Generated by RTL Generator\n");
    fprintf(output_file, "module %s(\n", config->module_name);
    fprintf(output_file, "    input clk,\n");
    fprintf(output_file, "    input rst_n\n");
    fprintf(output_file, ");\n\n");
    fprintf(output_file, "    // Input ports\n");
    for (i = 0; i < config->input_count; i++) {
        fprintf(output_file, "    // input [%d:0] input_%d;\n", 
                config->input_width[i] - 1, i);
    }
    fprintf(output_file, "\n    // Output ports\n");
    for (i = 0; i < config->output_count; i++) {
        fprintf(output_file, "    // output [%d:0] output_%d;\n", 
                config->output_width[i] - 1, i);
    }
    fprintf(output_file, "\n    // RTL logic goes here\n\n");
    fprintf(output_file, "endmodule\n");
}

void generate_testbench(ModuleConfig *config, FILE *output_file) {
    fprintf(output_file, "// Auto-generated Testbench\n");
    fprintf(output_file, "`timescale 1ns/1ps\n\n");
    fprintf(output_file, "module %s_tb;\n\n", config->module_name);
    fprintf(output_file, "    reg clk, rst_n;\n\n");
    fprintf(output_file, "    %s u0 (\n", config->module_name);
    fprintf(output_file, "        .clk(clk),\n");
    fprintf(output_file, "        .rst_n(rst_n)\n");
    fprintf(output_file, "    );\n\n");
    fprintf(output_file, "    // Clock generation\n");
    fprintf(output_file, "    initial begin\n");
    fprintf(output_file, "        clk = 0;\n");
    fprintf(output_file, "        forever #5 clk = ~clk;\n");
    fprintf(output_file, "    end\n\n");
    fprintf(output_file, "    // Reset and test sequence\n");
    fprintf(output_file, "    initial begin\n");
    fprintf(output_file, "        rst_n = 0;\n");
    fprintf(output_file, "        #20 rst_n = 1;\n");
    fprintf(output_file, "        #100 $finish;\n");
    fprintf(output_file, "    end\n\n");
    fprintf(output_file, "endmodule\n");
}

void print_help(void) {
    printf("RTL Generator - Verilog code generation tool\n\n");
    printf("Usage: rtl-gen [options]\n\n");
    printf("Options:\n");
    printf("  --module <name>    Module name\n");
    printf("  --inputs <widths>  Input port widths (comma-separated)\n");
    printf("  --outputs <widths> Output port widths (comma-separated)\n");
    printf("  --help             Show this help message\n");
}